TOPIC_LIST = [
    "Architecture",
    "Remodeling",
    "DIY",
    "Garden stuff",
    "Pop Culture",
    "Music News",
    "Actors",
    "Tik Tok",
    "K Pop",
    "Economics",
    "Stocks",
    "Investing",
    "Budgeting",
    "Crypto",
    "Retirement",
    "Fitness",
    "Healthy Living",
    "Women's Health",
    "Mens Health",
    "Sports",
    "Pro Sports",
    "Beauty",
    "Cleansing",
    "Technology",
    "Startups",
    "Big Tech",
    "Programming",
    "Graphic Design",
    "Programming",
    "Graphic Design",
    "Sports",
    "Stocks",
    "Weather",
    "Skincare",
    "Cleansing",
    "Crypto",
    "Healthy Living",
    "DIY",
    "Freelancing",
    "Blogging",
    "K Pop",
    "Math",
]
